singleQuote: true
plugins:
  - 'prettier-plugin-svelte'
  - 'prettier-plugin-astro'
overrides:
  [
    { files: '*.astro', options: { parser: 'astro' } },
    { files: '*.svelte', options: { parser: 'svelte' } },
  ]
